import type { CompanyInvoice, CompanyPayment } from "@/lib/data/companies";

const naira = (n: number) => `₦${Math.round(n).toLocaleString()}`;
const esc = (s: string) => s.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c] ?? c);

/**
 * Opens a print-optimised payment receipt in a new window and triggers the print
 * dialog (Save as PDF). Zero-dependency — the browser handles PDF generation.
 */
export function printPaymentReceipt(inv: Pick<CompanyInvoice, "company" | "paidToDate" | "outstanding">, payment: CompanyPayment) {
  const issued = new Date().toLocaleDateString();
  const receiptNo = `RCP-${payment.id.slice(0, 8).toUpperCase()}`;

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Receipt ${receiptNo} — ${esc(inv.company.name)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #211d18; margin: 40px; }
    .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #c9a84c; padding-bottom: 16px; }
    .brand { font-size: 22px; font-weight: 700; letter-spacing: .06em; }
    .doc { text-align: right; }
    .doc h1 { margin: 0; font-size: 20px; letter-spacing: .1em; }
    .muted { color: #928a7c; font-weight: 400; }
    h2 { font-size: 12px; text-transform: uppercase; letter-spacing: .08em; color: #928a7c; margin: 24px 0 6px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th, td { text-align: left; padding: 8px; border-bottom: 1px solid #e6dfd3; }
    th { color: #928a7c; font-weight: 600; font-size: 11px; text-transform: uppercase; }
    .r { text-align: right; }
    .amount { margin-top: 24px; padding: 16px; background: #f7f3ea; border-radius: 8px; display: flex; justify-content: space-between; align-items: baseline; }
    .amount .big { font-size: 24px; font-weight: 700; }
    .summary { margin-top: 20px; margin-left: auto; width: 280px; }
    .summary td { border: 0; padding: 4px 8px; }
    .out { color: #a3341f; font-weight: 600; }
    .thanks { margin-top: 32px; font-size: 13px; color: #928a7c; }
    @media print { body { margin: 16px; } }
  </style></head><body>
    <div class="head">
      <div>
        <div class="brand">ACEMCO EXPRESS</div>
        <div class="muted" style="font-size:12px">Warri, Delta State, Nigeria</div>
      </div>
      <div class="doc">
        <h1>RECEIPT</h1>
        <div class="muted" style="font-size:12px">${esc(receiptNo)}</div>
        <div class="muted" style="font-size:12px">${issued}</div>
      </div>
    </div>

    <h2>Received from</h2>
    <div><strong>${esc(inv.company.name)}</strong> <span class="muted">(${esc(inv.company.tier.toLowerCase())})</span></div>
    ${inv.company.billingEmail ? `<div class="muted" style="font-size:12px">${esc(inv.company.billingEmail)}</div>` : ""}

    <h2>Payment</h2>
    <table>
      <thead><tr><th>Date</th><th>Method</th><th>Reference</th><th class="r">Amount</th></tr></thead>
      <tbody>
        <tr>
          <td>${esc(payment.paidAt?.slice(0, 10) ?? issued)}</td>
          <td style="text-transform:capitalize">${esc(payment.method.toLowerCase())}</td>
          <td>${esc(payment.reference ?? payment.note ?? "—")}</td>
          <td class="r">${naira(payment.amount)}</td>
        </tr>
      </tbody>
    </table>

    <div class="amount">
      <span>Amount received</span>
      <span class="big">${naira(payment.amount)}</span>
    </div>

    <table class="summary">
      <tr><td>Paid to date</td><td class="r">${naira(inv.paidToDate)}</td></tr>
      <tr><td>Outstanding balance</td><td class="r out">${naira(inv.outstanding)}</td></tr>
    </table>

    <p class="thanks">Thank you for your payment. This receipt was generated by Acemco Express and is valid without a signature.</p>
  </body></html>`;

  const w = window.open("", "_blank", "width=800,height=1000");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}
